# Site settings
title: SCSS Compiler in PHP
current_version: 0.1.9
description: >
  SCSS compiler written in PHP
url: http://leafo.github.io
baseurl: /scssphp/
repo_url: https://github.com/leafo/scssphp
twitter_username: moonscript

# Build settings
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- Makefile
- composer.lock
- vendor/

# Github Pages
ghlighter: pygments
github: [Repository metadata]
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
