# Site settings
title: SCSS Compiler in PHP
email: leafot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  SCSS compiler written in PHP
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leafo.github.io/scssphp" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
current_version: 0.1.7
root: /scssphp

# Build settings
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- composer.lock
- serve.sh
- vendor/

# Github Pages
ghlighter: pygments
github: [Repository metadata]
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
